# eureka:
#     instance:
#     prefer-ip-address: true
#     client:
#     fetch-registry: true
#     register-with-eureka: true
#     serviceUrl:
#       defaultZone: ${eureka_service_url:http://localhost:8761/eureka}

spring:
  application:
    name: config-server 
  cloud:
    config:
      server:
        git:
          uri: ${repository_url:https://github.com/jczalson/eai-config-files.git}
          cloneOnStart: true
          username: ${user}
          password: ${token}
          default-label: ${branch-name:main}

server:
  port: 8888   
   
management:
  endpoints:
    web:
      exposure:
        include: health, refresh, conditions