spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/zalson/eai-config-files.git
          cloneOnStart: true
          password: ${token:glpat-8tuRYUbt7eQ4ZToVi5Gx}
          default-label: ${branch-name:main}
      

server:
  port: 8888    
